version: "3"

services:
  axon-server:
    container_name: "workshop-axon-server"
    #image: axoniq/axonserver-enterprise:4.5.15-dev
    image: axoniq/axonserver:4.5.12-jdk-17-dev
    hostname: axonserver
    environment:
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: "true"
      AXONIQ_AXONSERVER_SSL_ENABLED: "false"
      AXONIQ_AXONSERVER_ACCESSCONTROL_ENABLED: "false"
      AXONIQ_AXONSERVER_NAME: "localhost"
      AXONIQ_AXONSERVER_HOSTNAME: "localhost"
      AXONIQ_AXONSERVER_AUTOCLUSTER_FIRST: "localhost"
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
